import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{ADDRESS,EXPLORER,connect,read,waitFinalized,write}from'./genlayer.js';import{returnedId,VERSION}from'./transactions.js';

const EMPTY={owner:'',repository:'',base_commit:'',head_commit:'',package_name:'',package_version:'',production_prefix:'src',test_prefix:'tests'};
const SHORT=v=>v?`${v.slice(0,7)}…${v.slice(-5)}`:'Not configured';
const STAGES=['REGISTERED','RELEASABLE','ACTIVATED'];
function Field({label,name,value,onChange,placeholder}){return <label><span>{label}</span><input name={name} value={value} onChange={onChange} placeholder={placeholder}/></label>}
function App(){
 const[wallet,setWallet]=useState(null),[config,setConfig]=useState(null),[form,setForm]=useState(EMPTY),[releaseId,setReleaseId]=useState(''),[release,setRelease]=useState(null),[inspection,setInspection]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[tx,setTx]=useState('');
 const configured=/^0x[0-9a-f]{40}$/i.test(ADDRESS);
 async function syncConfig(){if(!configured)return;try{setConfig(await read('get_config'))}catch(e){setError(e.message)}}
 useEffect(()=>{syncConfig()},[]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 async function run(label,fn){setBusy(true);setError('');setNotice(label);try{await fn()}catch(e){setError(e.message);setNotice('')}finally{setBusy(false)}}
 async function load(id=releaseId){if(!/^\d+$/.test(String(id))||Number(id)<1)throw Error('Enter a valid release ID.');const exact=Number(id);const record=await read('get_release',[exact]);setReleaseId(String(exact));setRelease(record);if(record.attempts>0){try{setInspection(await read('get_inspection',[exact,record.attempts]))}catch{setInspection(null)}}else setInspection(null);setNotice(`Release #${exact} synced from authoritative contract state.`);return record}
 async function send(functionName,args,after){if(!wallet)throw Error('Connect a wallet first.');const hash=await write(wallet,functionName,args);setTx(hash);const receipt=await waitFinalized(hash,status=>setNotice(`${status} · waiting for authoritative readback`));return after(receipt)}
 async function register(){await run('Submitting release identity',async()=>{const args=[form.owner,form.repository,form.base_commit,form.head_commit,form.package_name,form.package_version,form.production_prefix,form.test_prefix];await send('register_release',args,async receipt=>{const id=returnedId(receipt);const r=await load(id);if(r.state!=='REGISTERED')throw Error('Readback did not match REGISTERED.');setNotice(`Release #${id} registered and verified by readback.`)})})}
 async function inspect(){await run('Inspecting GitHub and npm authority sources',async()=>send('inspect_release',[Number(releaseId)],async()=>{const r=await load(releaseId);if(r.state==='REGISTERED')throw Error('Readback did not advance the release.');setNotice(`Inspection finalized: ${r.state}.`)}))}
 async function activate(){await run('Activating exact artifact commitment',async()=>send('activate_release',[Number(releaseId),release.artifact_integrity],async()=>{const r=await load(releaseId);if(r.state!=='ACTIVATED')throw Error('Activation readback mismatch.');setNotice('Exact release artifact activated on-chain.')}))}
 async function walletConnect(){await run('Connecting wallet',async()=>{const w=await connect();setWallet(w);setNotice(`Connected ${SHORT(w.account)}`)})}
 const primary=release?.state==='RELEASABLE'?{text:'Activate exact artifact',action:activate}:release?.state==='REGISTERED'||release?.state==='UNRESOLVED'?{text:release.state==='UNRESOLVED'?'Retry inspection':'Inspect authoritative sources',action:inspect}:null;
 const progress=useMemo(()=>release?.state==='ACTIVATED'?3:release?.state==='RELEASABLE'?2:release?1:0,[release]);
 return <main>
  <header><a className="brand" href="#top"><img src="/release-seal-logo.png"/><span><b>ReleaseSeal</b><small>source → checks → artifact</small></span></a><div className="network"><i/>StudioNet · {SHORT(ADDRESS)}</div><button className="wallet" onClick={walletConnect} disabled={busy}>{wallet?SHORT(wallet.account):'Connect wallet'}</button></header>
  <section className="hero" id="top"><div className="eyebrow">INTELLIGENT RELEASE GATE · {VERSION}</div><h1>Ship what<br/><em>you actually built.</em></h1><p>ReleaseSeal compares an exact GitHub diff, head-bound CI results and npm artifact metadata before an immutable release can be activated.</p><div className="source-strip"><span>GITHUB COMMIT</span><b>+</b><span>CHECK RUNS</span><b>+</b><span>NPM INTEGRITY</span><strong>CONSENSUS</strong></div></section>
  <section className="workspace">
   <aside><div className="aside-title">Release route</div>{STAGES.map((s,i)=><div className={`stage ${progress>i?'done':''}`} key={s}><span>{String(i+1).padStart(2,'0')}</span><div><b>{s[0]+s.slice(1).toLowerCase()}</b><small>{i===0?'Bind exact revision':i===1?'Verify independent facts':'Consume once'}</small></div></div>)}<div className="boundary"><b>Proof boundary</b><p>RELEASABLE proves alignment of the observed source, checks and package metadata. It does not prove the software is bug-free or production-safe.</p></div></aside>
   <div className="console">
    <div className="console-head"><div><span>01 / REGISTER</span><h2>Pin a release candidate</h2></div><div className={`status ${configured?'ok':''}`}>{configured?'CONTRACT READY':'AWAITING DEPLOYMENT'}</div></div>
    <div className="form-grid"><Field label="GitHub owner" name="owner" value={form.owner} onChange={change} placeholder="acme"/><Field label="Repository" name="repository" value={form.repository} onChange={change} placeholder="protocol-sdk"/><Field label="Base commit · 40 hex" name="base_commit" value={form.base_commit} onChange={change} placeholder="parent revision"/><Field label="Head commit · 40 hex" name="head_commit" value={form.head_commit} onChange={change} placeholder="release revision"/><Field label="npm package" name="package_name" value={form.package_name} onChange={change} placeholder="protocol-sdk"/><Field label="Version" name="package_version" value={form.package_version} onChange={change} placeholder="1.4.0"/><Field label="Production path" name="production_prefix" value={form.production_prefix} onChange={change}/><Field label="Regression path" name="test_prefix" value={form.test_prefix} onChange={change}/></div>
    <button className="primary" onClick={register} disabled={busy||!wallet||!configured}>Register exact candidate <span>→</span></button>
    <div className="divider"><span>OR OPEN AN EXISTING RELEASE</span></div><div className="lookup"><input value={releaseId} onChange={e=>{setReleaseId(e.target.value);setRelease(null);setInspection(null)}} placeholder="Release ID"/><button onClick={()=>run('Loading release',()=>load())} disabled={busy||!configured}>Load authoritative state</button></div>
   </div>
  </section>
  {release&&<section className="readback"><div className="seal"><span>#{release.id}</span><b>{release.state}</b><small>{release.reason||'Awaiting inspection'}</small></div><div className="facts"><div><span>Repository</span><b>{release.owner}/{release.repository}</b></div><div><span>Head revision</span><b>{release.head_commit}</b></div><div><span>Package</span><b>{release.package_name}@{release.package_version}</b></div><div><span>Artifact integrity</span><b>{release.artifact_integrity||'Not established'}</b></div>{inspection&&<><div><span>CI binding</span><b>{inspection.checks_bound} · {inspection.checks_passed}</b></div><div><span>Regression alignment</span><b>{inspection.test_alignment}</b></div></>}</div>{primary&&<button className="primary inverse" onClick={primary.action} disabled={busy}>{primary.text}<span>→</span></button>}</section>}
  {(notice||error||tx)&&<section className={`receipt ${error?'bad':''}`}><div><span>{error?'ACTION STOPPED':'TRANSACTION TRACE'}</span><b>{error||notice}</b></div>{tx&&<a href={`${EXPLORER}/tx/${tx}`} target="_blank">Open finalized transaction ↗</a>}</section>}
  <section className="how"><div><span>HOW IT WORKS</span><h2>Three facts.<br/>One enforceable seal.</h2></div><ol><li><b>Bind</b><p>Register full base/head revisions and exact package coordinates.</p></li><li><b>Inspect</b><p>Validators fetch GitHub and npm endpoints constructed by the contract.</p></li><li><b>Enforce</b><p>Only the exact integrity value from a RELEASABLE record can activate once.</p></li></ol></section>
  <footer><span>ReleaseSeal · permissionless by construction</span><a href={configured?`${EXPLORER}/address/${ADDRESS}`:'#'} target="_blank">Contract explorer ↗</a></footer>
 </main>
}
createRoot(document.getElementById('root')).render(<App/>);
